### ISSUE TITLE
cannot connect

### ISSUE THREAD

**Issue by ehabtanta** [awidegreen/tr064#2]
i have done every thing as it should be build and make 
but the tool cannot connect to my device :it takes alot of time without making any action or output 
 however i am able of opening the xml file of the tr064 service  in my browser as shown 
is there any service of protocol that needs to be added to centos so that the tool work successfully

tnx for helping

**Comment by awidegreen** [comment]
thanks for this issue.
Does `tr064tool -v -L http://192.168.1.1:37215/tr064dev.xml` (note the `-v`) give you any more output?

**Comment by ehabtanta** [comment]
this seems to work will let the issue open for some hours to complete the test and make sure every thing is ok 

tnx veeeeeeeeeeeeeeeeery much

**Comment by ehabtanta** [comment]
no need

**Comment by ehabtanta** [comment]
tried debug build and this is its output

Going to use default username: admin
[LOG:trace] tr064.cc:276 : Found action in service!
[LOG:trace] Session.cc:26 : Going to execute Service: private data with action: private data
[LOG:trace] Auth.cc:121 : Current state: IDLE
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:debug] HttpConnection.cc:59 : Connect attempts: 1 connected to: 192.168.1.1:37215
[LOG:trace] HttpConnection.cc:82 : Request send.
[LOG:debug] HttpConnection.cc:92 : 1. read for read_untl "\r\n": 36
An error occured: std::exception
[root@localhost src]#

**Comment by ehabtanta** [comment]
maybe cuz the issue closed and reopened it is not active will close it and open a new one
