### ISSUE TITLE
use the tool with no authentication 

### ISSUE THREAD

**Issue by ehabtanta** [awidegreen/tr064#3]

**Comment by awidegreen** [comment]
Have you check the manpage? `man -l man/man1/tr064tool.1` ?

Regarding username and password:

```
       -u, --user username
              Specifies a user name which is used for executing service actions, default admin.

       -p, --password password
              Specifies a password which is used for executing service actions, default gurkensalat.
```

Unfortunately, you can not override the default user or password at the moment. However,  I recommend using the `-u` and `-p` options.

Further, so far I always assumed that an authentication when executing actions is required. Hence you need to provide a username and password.

**Comment by ehabtanta** [comment]
i think the issue is in the modem it doesn't require  auth 
i tried it with another upnp software and is works like a dream but the other soft only works on the upnpdev.xml  

i have already tried my own pwd before posting the issue but in vain also tried to add user acording to your instructions but it gave the same output the router's auth is always idle as it doesn't require it 

i know the user name and can change the pwd any time as i like but the router doesn't invoke the aut process 
so pleas can u tell me how to make the tr064tool ignore the auth part and deal directly with the control points

thank you alot i am really greatful

**Comment by ehabtanta** [comment]
I am eagerly awaiting  your response  I wish  that you  reply  today
Thanks

**Comment by awidegreen** [comment]
I'm not quite sure why the exception occurs. Are you able to get an wireshark capture of the response? 

As for the support for no-auth required... that needs to be implemented. Not sure if will have time for that this week. Otherwise, feel free to try it yourself and send a PullRequest. ;)

**Comment by ehabtanta** [comment]
i am more than grateful for you u r very kind and patient GOD bless you 

i made an wireshark capture of the response but i dont know how to attach it here so i made a screen shot of the action area of the packet 
![ws](https://cloud.githubusercontent.com/assets/12570882/8091929/0aee07b6-0fb7-11e5-88e5-7484b6d0dd45.png)

and here is the full comand output 

[root@localhost Desktop]# '/root/Desktop/tr064/x/src/tr064tool' UserInterface:GetLoginUsername -v -L http://192.168.1.1:37215/tr064dev.xml
Fetch resource (GET) http://192.168.1.1:37215/tr064dev.xml
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
Fetch resource (GET) http://192.168.1.1:37215/desc/UserItf.xml
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
Fetch resource (GET) http://192.168.1.1:37215/desc/DevCfg.xml
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
Fetch resource (GET) http://192.168.1.1:37215/desc/LANSec.xml
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
Fetch resource (GET) http://192.168.1.1:37215/desc/L3Fwd.xml
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
Fetch resource (GET) http://192.168.1.1:37215/desc/DevUpg.xml
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
Fetch resource (GET) http://192.168.1.1:37215/desc/WanDslIfCfg.xml
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
Fetch resource (GET) http://192.168.1.1:37215/desc/WanCommonIfc1.xml
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
Fetch resource (GET) http://192.168.1.1:37215/desc/WanPppConn.xml
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
Fetch resource (GET) http://192.168.1.1:37215/desc/WanDslLink.xml
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
Fetch resource (GET) http://192.168.1.1:37215/desc/WanPppConn.xml
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
Fetch resource (GET) http://192.168.1.1:37215/desc/WanDslLink.xml
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
Fetch resource (GET) http://192.168.1.1:37215/desc/WLANCfg.xml
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
Fetch resource (GET) http://192.168.1.1:37215/desc/WLANCfg.xml
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
Fetch resource (GET) http://192.168.1.1:37215/desc/WLANCfg.xml
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
Fetch resource (GET) http://192.168.1.1:37215/desc/WLANCfg.xml
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
Fetch resource (GET) http://192.168.1.1:37215/desc/LanHostCfgMgmt.xml
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
Going to use default password: gurkensalat
Going to use default username: admin
[LOG:trace] tr064.cc:266 : Found action in service!
[LOG:trace] Session.cc:26 : Going to execute Service: UserInterface with action: GetLoginUsername
[LOG:trace] Auth.cc:121 : Current state: IDLE
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
An error occured: std::exception

if the   .pcapng  file was needed i will be more than happy to upload it and share the link 

As for the support for no-auth   
i will do my best but i dont know what really should be done i am thinking of changing the auth response to make is always as the authenticated one or even remove the auth part from the Session.cc
which would be more efficient 
would you please tell me where to start ?

i will do all i can before bothering you with a  PullRequest.

**Comment by awidegreen** [comment]
The application should crash, but I noticed that your device returns `500 Internal Server Error`

```
HTTP/1.0 500 Internal Server Error
Content-Type: text/xml; charset="utf-8"
Server: Linux UPnP/1.0 Huawei-ATP-IGD
EXT: 
Connection: Keep-Alive
Content-Length: 398
```

Any idea why?

**Comment by ehabtanta** [comment]
i was researching that i see no good reason as the device is doing all other tasks as it should and replies for the upnpdev.xml but this is form a windows application 

i will try executing some other actions with  our tool to see what would the response be 

but dose this means that the Keep-Alive is to short to give response? 
i think i can change the deferant apps time out in the telnet ATP  but I need THE RIGHT MODULE NAME WILL TRY THIS TOO
thanx 

will keep you updated with news

**Comment by awidegreen** [comment]
do you have or if not can you try to enable user authentication on the device, does that make any difference?

**Comment by ehabtanta** [comment]
the disable/enable auth is only available for cwmp(tr069)
for tr064 all is there is the change pwd option the telnet commands are very limited 
i searched for the tools and found those interesting two   libupnpapi.a  libatputil.so   i made there time 500s 
tried some other actions from other services but the same output 

Going to use default username: admin
[LOG:trace] tr064.cc:266 : Found action in service!
[LOG:trace] Session.cc:26 : Going to execute Service: WLANConfiguration with action: GetChannelInfo
[LOG:trace] Auth.cc:121 : Current state: IDLE
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
An error occured: std::exception


i noticed that the device have multi devices under its tree like this 
RootDevice details:
  locaion: http://192.168.1.1:37215/tr064dev.xml
  server: 
  cache_ctrl: 
  search_type: 
  usn: 
  device_desc_doc: /tr064dev.xml
  host: 192.168.1.1
  port: 37215
--------------------------------------------
================ All devices: ==============
Device: InternetGatewayDevice
     Service: UserInterface
          Action: GetLoginUsername
Device: WANDevice
     Service: WANDSLInterfaceConfig
          Action: GetInfo
     Service: WANCommonInterfaceConfig
          Action: SetEnabledForInternet
          Action: GetEnabledForInternet
          Action: GetCommonLinkProperties
          Action: GetTotalBytesSent
          Action: GetTotalBytesReceived
          Action: GetTotalPacketsSent
          Action: GetTotalPacketsReceived
Device: LANDevice
     Service: WLANConfiguration
          Action: GetInsecureOutOfBandAccessMode
          Action: SetEnable
          Action: GetEnable


how would i tell the tool what device to deal with ?
but it always finds the action in the service so i dont think this would be the case

**Comment by awidegreen** [comment]
I see. Since every service is unique for each device, I designed it to just specify the service and action you wanna execute, hence the parameter `<service_name>:<action name>`

I could try to provide an option to connect without user credentials, I just wonder how the request would look like... need to do some research to find that out.

**Comment by awidegreen** [comment]
Hi again f58c36b78da3fddb74993f5c23695ed518cee922 introduces `--no-auth` parameter (see manpage). Also I fixed the reporting of the exception, so it will now be printed what the error was. 

Therefore please pull and recompile and try again. thanks

**Comment by ehabtanta** [comment]
u are a real bliss for me on the other side i am also doing my best 
 after hours of search i found some good info that i used and with some trying i found that this modem needs auth and the specific action that i was testing is not implemented (don't know why would a router offer a non implemented action )

also discovered some thing that may be very important 

WWW-Authenticate: Digest realm="HuaweiHomeGateway",nonce="c958321c6f439a0864c6aa39ba9e9d87", qop="auth", algorithm="MD5"\r\n

this is where the modem receives the auth data as i think 

xmlns:h="http://soap-authentication.org/digest/2001/10/"

and this is where the tool directs that type of data 

so if my thoughts where right this could be an important piece of work to be done 
this is the wireshark capture for the command 

'/root/Desktop/tr064/x/src/tr064tool' WANPPPConnection:GetUserName -udslf-config -padmin -v -L  http://192.168.1.1:37215/tr064dev.xml

https://www.dropbox.com/s/98m4oxd5q2bytll/2.pcapng?dl=0

will try the no auth with some other upnp actions thanks aloot for it

**Comment by ehabtanta** [comment]
the new test result 
'/root/Desktop/tr06/x/src/tr064tool' Layer3Forwarding:GetDefaultConnectionService --no-auth  -v -L  http://192.168.1.1:37215/tr064dev.xml

gives 
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
[LOG:trace] tr064.cc:281 : Found action in service!
[LOG:trace] Session.cc:26 : Going to execute Service: Layer3Forwarding with action: GetDefaultConnectionService
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
[LOG:trace] Auth.cc:164 : Current state: IDLE
An error occured: [Auth:handle_auth_response] Unable to proceed in State: IDLE

and

'/root/Desktop/tr06/x/src/tr064tool' Layer3Forwarding:GetDefaultConnectionService -v -L  http://192.168.1.1:37215/tr064dev.xml

gives

[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
Going to use default password: gurkensalat
Going to use default username: admin
[LOG:trace] tr064.cc:281 : Found action in service!
[LOG:trace] Session.cc:26 : Going to execute Service: Layer3Forwarding with action: GetDefaultConnectionService
[LOG:trace] Auth.cc:121 : Current state: IDLE
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
[LOG:trace] Auth.cc:164 : Current state: INIT_CHALLANGE
An error occured: The Authentication should have failed for the initial SOAP auth. challenge.


and with u & p
 '/root/Desktop/tr06/x/src/tr064tool' Layer3Forwarding:GetDefaultConnectionService -uadmin -pehab -v -L  http://192.168.1.1:37215/tr064dev.xml

Going to use default username: admin
[LOG:trace] tr064.cc:281 : Found action in service!
[LOG:trace] Session.cc:26 : Going to execute Service: Layer3Forwarding with action: GetDefaultConnectionService
[LOG:trace] Auth.cc:121 : Current state: IDLE
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.
[LOG:trace] Auth.cc:164 : Current state: INIT_CHALLANGE
An error occured: The Authentication should have failed for the initial SOAP auth. challenge.
[root@localhost src]# 

note that i can access the web interface of the device using user admin & pass  ehab

but the strang thing is that it takes about 100 seconds to give the final result 

it halts on 
[LOG:trace] HttpConnection.cc:41 : Try to open a socket to: 192.168.1.1 on port: 37215
[LOG:trace] HttpConnection.cc:82 : Request send.

for some time then continues
before it gave the result instantly

**Comment by ehabtanta** [comment]
for now i tried all the possible user names 

admin
root
tr064
dslf-config
dslf-reset 

and always it gives 401 
maby cuz they are being directed to some area other that what should be 
and the header of the request only contained a user name with no pwd 

here is an example wireshark file
https://www.dropbox.com/s/b36g6cjosqcd2or/3.pcapng?dl=0

i also had some default pwd that is !@HuaweiHgw  but the tool didn't accept 
bash: !@HuaweiHgw: event not found

**Comment by awidegreen** [comment]
How did you specify the password in the last execution? I hope you used: `-p "!@HuaweiHgw"`

I found a fault in Session.cc, therefore you got `An error occured: [Auth:handle_auth_response] Unable to proceed in State: IDLE`

Will try to fix and push it.

**Comment by awidegreen** [comment]
I just pushed 0cd64520781d0988462103342a6478812e3278e3 I would appreciate if you can try it again. The problem was that I did not handle the "no auth" all the way through. Sorry ;)

**Comment by ehabtanta** [comment]
i have searched the results for some time it is about the 

WWW-Authenticate: Digest realm="HuaweiHomeGateway",nonce="94eef7ae62f727ba43f5ef5833648d6b", qop="auth", algorithm="MD5"\r\n

in the digest auth way the router will always respond with a 401 then we should  processes some data and sent it back again 

it is better described here 

https://en.wikipedia.org/wiki/Digest_access_authentication

**Comment by ehabtanta** [comment]
now all we need is to respond to the 401 with the calculated hash of the following 

Authorization: Digest username="admin",
                     realm="HuaweiHomeGateway",
                     nonce="94eef7ae62f727ba43f5ef5833648d6b",
                     uri="/ctrlt/WANPPPConnection_1",   that could be changed acording to control point
                     qop=auth,

i dont really know hot to generate those but it would be done by some md5 hashing the current pwd would be null  
                      nc=00000001,
                     cnonce="0a4f113b",
                     response="6629fae49393a05397450978507c4ef1",

**Comment by ehabtanta** [comment]
from anlysing the wirshark pakets i found that the tool only sends a user name with no pwd could  this be the reason for the 401

<?xml
version="1.0"
encoding="utf-8"
?>
<s:Envelope
s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
<s:Header>
<h:InitChallenge
xmlns:h="http://soap-authentication.org/digest/2001/10/"
s:mustUnderstand="1">
<UserID>
admin
</UserID>
</h:InitChallenge>
</s:Header>
<s:Body>
<u:GetUserName
xmlns:u="urn:dslforum-org:service:WANPPPConnection:1">
</u:GetUserName>
</s:Body>
</s:Envelope>

and the 401 comes at the level of http not the .xml 
could we also send the auth data on the same level (not sure if this could work )

**Comment by awidegreen** [comment]
well .. as you already figured out; digest access authentication like this is not support yet. :) 
Currently only the SOAP ext Basic and Digest Authentication is used, http://www.whitemesa.com/soapauth.html#S424

**Comment by ehabtanta** [comment]
ok ty very much i thought that yhe router works in WWW-Authenticate: Digest  as stated in the 401 header so what is the deferance between  WWW-Authenticate: Digest & digest access authentication & Digest Authentication   I THOUGHT THAT THEY ALL ARE ONE THING 
and there is one last point that is uncleare why the tool only sents the user name without the pass in the request header ?


can u please tell me of any tool\app\repo that supports the WWW-Authenticate: Digest with tr064 cuz now i know the user& pwd but dont know how to send them to the router


thanks very much

**Comment by ehabtanta** [comment]
tnx alot
