### ISSUE TITLE
Client UPnPError

### ISSUE THREAD

**Issue by ehabtanta** [awidegreen/tr064#4]
hi again

i was tring to get this work by other means but i weren't able to find any better tool or support than your's :+1: +1:  

so i made anew clean install of centos 
and the tools 
i now know the username and pwd for sure 

tried the tool just to encounter another new error :
the tool command :

 '/root/Desktop/tr064/x/src/tr064tool' UserInterface:GetLoginUsername --no-auth -v -L http://192.168.1.1:37215/tr064dev.xml

An error occured: Invalid HTTP response code: code: 500 version: HTTP/1.0 message: Internal
this is the tool output 

and this is the wireshark tcp stream :

```
POST /ctrlt/UserInterface_1 HTTP/1.1
HOST: 192.168.1.1
CONTENT-LENGTH: 307
CONTENT-TYPE: text/xml; charset="utf-8"
SOAPACTION: "urn:dslforum-org:service:UserInterface:1#GetLoginUsername"
CONNECTION: close
USER-AGENT: AVM UPnP/1.0 Client 1.0 - tr064 lib



<?xml version="1.0" encoding="utf-8"?>
<s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Body>
    <u:GetLoginUsername xmlns:u="urn:dslforum-org:service:UserInterface:1">
    </u:GetLoginUsername>
  </s:Body>
</s:Envelope>
HTTP/1.0 500 Internal Server Error
Content-Type: text/xml; charset="utf-8"
Server: Linux UPnP/1.0 Huawei-ATP-IGD
EXT: 
Connection: Keep-Alive
Content-Length: 398

<s:Envelope
xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<s:Body>
<s:Fault>
<faultcode>s:Client</faultcode>
<faultstring>UPnPError</faultstring>
<detail>
<UPnPError xmlns="urn:schemas-upnp-org:control-1-0">
<errorCode>501</errorCode>
<errorDescription></errorDescription>
</UPnPError>
</detail>
</s:Fault>
</s:Body>
</s:Envelope>
```

can u help me solve this 
dose the tool contain the line 

urn:schemas-upnp-org:control-1-0

cuz it dosent corrspond to and  my upnpdev.xml  & tr064dev.xml files 

tnx aloot

**Comment by ehabtanta** [comment]
i have also discovered that the tool sends some requests without the auth header and some others  with the auth header only containing the username without the pwd  
- i didn't use the --no-auth 

some requests were fulfilled but the tool didn't get the response i extracted it from wireshark

is it possible to make the tool send poth the username& pwd in the header of the soap request?

tnx

**Comment by awidegreen** [comment]
I'm currently looking into changing the HTTP req/resp stuff to use libcurl (will introduce HTTP authentication support).

I'm not quite sure what errorCode `501` means ... and the descriptions isn't very obvious either: http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.0.pdf (p.53) 

```
501 - Action Failed - May be returned in current state of service prevents invoking that action.
```

Seems that the user does not have permission to execute the action.

**Comment by ehabtanta** [comment]
thanks alot i thinks so about the 501 it means that there are no implementation for invoking the actions without auth 

CURL will be very useful and powerful add-on  

i am really happy that there is still such good and caring people like you thanks aloooot

**Comment by ehabtanta** [comment]
can u please help me make the right SOAPAction request using curl with the following form 

curl -H "Content-Type: text/xml; charset=utf-8" \
-H "SOAPAction:urn:dslforum-org:service:UserInterface:1#GetLoginPassword" \
-d @soap.txt -X POST http://192.168.1.1/ctrlt/UserInterface_1

while soap.txt   is 

https://www.dropbox.com/s/vx60kagbx6qv1k9/curl%20no%20aut?dl=0

is this right ?
how to add auth to it 

there are the xml files from the router that are related to the request 

the tr064 file 
https://www.dropbox.com/s/00c7enso6anywg5/tr064dev.xml?dl=0

the service we want to work on is 
urn:dslforum-org:service:UserInterface:1

the UserItf file of the service 
https://www.dropbox.com/s/c4aucn3ovznkql9/UserItf.xml?dl=0

starts with 
<scpd xmlns="urn:schemas-upnp-org:service-1-0">

and the action we need to invoke is GetLoginPassword

the current username for the tr064 is :dslf-config
and the pwd is :admin
the relame is : HuaweiHomeGateway
qop:auth

thanks

**Comment by awidegreen** [comment]
How come you use `UserInterface_1` I can not find that ctrl url in the provided `tr064dev.xml`?

Further you should be able to construct the HTTP req with this guide http://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AVM_TR-064_first_steps.pdf (that is what I used to implement this tool), chapter 10 for examples.

**Comment by ehabtanta** [comment]
sorry the file i posted earlier was a wrong one this is the one i am dealing with 

https://www.dropbox.com/s/bnlh3vt9qlo7zc8/right%20tr064dev.xml?dl=0

and actually this is one of the problem that faces me 
i don't know where to send the request 

the host : 192.168.1.1
the port:37215 (tcp) or 1900 (udp)
the tr064 module : 192.168.1.1:37215/tr064dev.xml
the service id  :UserInterface1

service>
serviceType>urn:dslforum-org:service:UserInterface:1</serviceType>
serviceId>urn:dslforum-org:serviceId:UserInterface1</serviceId>
SCPDURL>/desc/UserItf.xml</SCPDURL>
controlURL>/ctrlt/UserInterface_1</controlURL>
eventSubURL>/evt/UserInterface_1</eventSubURL>
/service>
the action name ::GetLoginPassword

thnx for the guide will check it and see if it supports auh 

thanks alot boss

**Comment by ehabtanta** [comment]
so i was foling around the frimware file and fond that it is a grop of elf flies led by busybox 
and a group of lib***.so files and some other files 
i tried my best to edit them or read them and the useful info i could get was that chunk of data 
i thought u might be able to get any helpful data from it 
 i put in in a file 
https://www.dropbox.com/s/zq4q2s08gbvv8zh/data%20from%20upnp%20ELF.txt?dl=0

and here it is in raw format 
atpv......%s....s:t:r...Upnp: cms is not ready, wait for next chance....upnp....tr064 reg msg/db proc failed:%X...../etc/upnp...Fatal error, create upnp stack failed...Create upnp http socket failed: %d....../etc/root.pem.../etc/servercert.pem./etc/serverkey.pem..Create tr064 https socket failed: %d....Can not start https socket..NOTIFY..M-SEARCH....SUBSCRIBE...UNSUBSCRIBE.NT..NTS.USN.MAN.MX..ST..EXT.TIMEOUT.CALLBACK....brctl addbr br0:9 2> /dev/null..ifconfig br0:9 169.254.100.156 netmask 255.0.0.0 2> /dev/null...ifconfig br0:9 up 2> /dev/null..169.254.100.156.ifconfig br0:9 down 2> /dev/null....brctl delbr br0:9 2> /dev/null..mic.route add -net 239.0.0.0 netmask 255.0.0.0 dev br0..Huawei Model....http://www.huawei.com...000000000001....239.255.255.250.Get pub info from shm failed....Layer3Forwarding....L3Forwarding....WANCommonInterfaceConfig....WANCommonIFC....WANPOTSLinkConfig...WANPOTSLinkC....WANDSLLinkConfig....WANDSLLinkC.WANCableLinkConfig..WANCableLinkC...WANEthernetLinkConfig...WANEthLinkC.WANPPPConnection....WANPPPConn..WANIPConnection.WANIPConn...LANHostConfigManagement.LANHostCfg..........................................................New.FCSPreserved....AutoConfig..EnabledForInternet..SubnetMask..255.255.255.0...DHCPRelay...UpstreamMaxBitRate..DownstreamMaxBitRate....InternetGatewayDevice.LANDevice.1.X_WLANEnable..InternetGatewayDevice.DeviceInfo.SoftwareVersion....SoftwareVersion.WEPKey.%d.WEPKey....WEPKey%d....PreSharedKey.1.PreSharedKey.PreSharedKey....NATEnabled..RSIPAvailable...NewRemoteHost...NewExternalPort.NewProtocol.NewInternalPort.NewInternalClient...NewEnabled..NewPortMappingDescription...NewLeaseDuration....NewPortMappingIndex.WPA11iEncryptionModes...WPA11iAuthenticationMode....NewPassword.RemoteHost..ExternalPort....Protocol....cms.InternalPort....InternalClient..Enabled.false...true....PortMappingDescription..WANDevice.1.....WANDSLInterfaceConfig...LinkType....EoA.LinkStatus..NewSecurityPort.NewStatus...ChangesApplied..NewSessionID....NewDownloadURL..NewStatusURL....upg -g -U %s -t '1 Firmware Upgrade Image' -c upnp -r %s -d -b..InternetGatewayDevice:1.urn:www-huawei-com:service:DeviceUpgrade:1..DevUpg.xml..Layer3Forwarding:1..L3Fwd.xml...LANConfigSecurity:1.LANSec.xml..urn:www-huawei-com:service:DeviceConfig:1...DevCfg.xml..WANDevice:1.WANCommonInterfaceConfig:1..WanCommonIfc1.xml...WANDSLInterfaceConfig:1.WanDslIfCfg.xml.WANConnectionDevice:1...WANDSLLinkConfig:1..WanDslLink.xml..WANIPConnection:1...WanIpConn.xml...WANPPPConnection:1..WanPppConn.xml..LANDevice:1.LANHostConfigManagement:1...LanHostCfgMgmt.xml..WLANConfiguration:1.WLANCfg.xml.Upgrade.GetSoftwareVersion..SetSecurityKeys.SetEnable...SetPreSharedKey.SetWPA11iBeaconSecurityProperties...GetSecurityKeys.GetEnable...SetConfigPassword...ConfigurationStarted....ConfigurationFinished...GetSecurityPort.Reboot..GetDSLLinkInfo..AddPortMapping..DeletePortMapping...GetGenericPortMappingEntry..GetSpecificPortMappingEntry.GetNATRSIPStatus....GetLinkLayerMaxBitRates.SetDHCPRelay....GetDHCPRelay....SetSubnetMask...GetSubnetMask...SetEnabledForInternet...GetEnabledForInternet...RequestConnection...ForceTermination....GetAutoConfig...SetFCSPreserved.GetFCSPreserved.SetDSLLinkType..SetDestinationAddress...SetATMEncapsulation.SetConnectionType...GetUserName.GetPassword.SetUserName.SetPassword.SetIPInterfaceInfo..SetDNSServers...SetSSID.SetBeaconType...SetRadioMode....SetChannel..SetDefaultWEPKeyIndex...SetBasBeaconSecurityProperties..SetWPABeaconSecurityProperties..Set11iBeaconSecurityProperties..SetWEPEncryptionLevel...........................................................................................................................................................................................................HG532eV100R001C136B011 UPNP <libupnpapi.a> V1.02....%s%d....NOTIFY %s HTTP/1.1..HOST: %s:%d..CONTENT-TYPE: text/xml..CONTENT-LENGTH: %d..NT: upnp:event..NTS: upnp:propchange..SID: uuid:%s..SEQ: %d....%s%s....<?xml version="1.0"?>...propertyset.xmlns...urn:schemas-upnp-org:event-1-0..property....dslf-config.dslf-reset..Linux UPnP/1.0 Huawei-ATP-IGD...max-age=%d..%s::upnp:rootdevice.%s::%s..uuid:...text/xml; charset="utf-8"...Keep-Alive..<s:Envelope.xmlns:s="http://schemas.xmlsoap.org/soap/envelope/".s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">.<s:Body>.<s:Fault>.<faultcode>s:Client</faultcode>.<faultstring>UPnPError</faultstring>.<detail>.<UPnPError xmlns="urn:schemas-upnp-org:control-1-0">.<errorCode>%d</errorCode>.<errorDescription>%s</errorDescription>.</UPnPError>.</detail>./s:Fault./s:Body./s:Envelope..rb..%a, %d %b %Y %H:%M:%S GMT...<?xml version="1.0"?>.%s..../ctrlu/.Header..SessionID...Body....%sResponse..tr064 set action(%s) failed !...upnp set action(%s).[param %s, value:%s].... success !..tr064 set action(%s) failed, ErrorCode: %d!.infinite....ATP UPnP Core...Second-%d...ssdp:discover...MX  invalid <%c>..../upnpdev.xml..../var..../tr064dev.xml.../icon/..%s/%s.../desc/..File not found......*...239.255.255.250:1900....ssdp:alive..ssdp:byebye.::..................................................................................%s.%d...%s../evt/.../ctrlt/.%s%s_%d.dslforum-org....schemas-upnp-org....urn:%s:%s:%s....service.device..uuid:%s%2.2x-%2.2x%2.2x%2.2x%2.2x%2.2x%2.2x.00e0fc37-2525-2828-25...00e0fc37-2626-2828-26...upnp:all....ssdp:all....%s_%d...Enable Got value: %d....NATEnabled Got value: %d....pstLast is null.%sWANCommonInterfaceConfig.WANAccessType....DSL.WANEthernetLinkConfig:1.Ethernet....urn:....action.argumentList.argument....argument.direction..in..out.argument.name...argument.relatedStateVariable...scpd.actionList.cfmNodeName.scpd.serviceStateTable.stateVariable....sendEvents..yes.stateVariable.name..dftValue....scpd.actionList.action..attr....action.name.%s%s....%s%d....deviceType..friendlyName....manufacturer....manufacturerURL.modelDescription....modelName...modelNumber.modelURL....serialNumber....UDN.UPC.iconList....icon....mimetype....width...height..depth...url.serviceList.urn:%s:%s:%s%d..serviceId...urn:upnp-org:serviceId..%s%c%s%c....SCPDURL.controlURL..eventSubURL.deviceList..http://%s...presentationURL.serviceType.root....urn:schemas-upnp-org:device-1-0.specVersion.major...minor...wb..<?xml version="1.0"?>...http://%s:%d%s..Malloc memory failed!%s.UpnpGetDeviceOrService..uuid:%s.Subscription %s:%s expired......subscribe list internal error

**Comment by ehabtanta** [comment]
AND ALSO I FOUND this interesting value 
is there any way to trace it to origin and get the info of the firmware default vales ?

https://www.dropbox.com/s/ui4u1o8dwsrpf1e/Untitled.jpg?dl=0

**Comment by ehabtanta** [comment]
hi sir
are u done with the libcurl integration yet ?

tnx

**Comment by awidegreen** [comment]
I just merged everything to master. Make sure that you have libcurl installed
