### ISSUE TITLE
digest auth not complete

### ISSUE THREAD

**Issue by ehabtanta** [awidegreen/tr064#5]
thanx for all your previous replies 
i tried with the new modifications but no luck the digest auth should be 2 steps but in the tool it halts after the first step 

[root@localhost src]# '/root/Desktop/tr064/build/src/tr064tool' LANConfigSecurity:SetConfigPassword -u "dslf-reset" -p "admin" -v  -L http://192.168.1.1:37215/tr064dev.xml

[LOG:trace] tr064.cc:281 : Found action in service!
[LOG:trace] Session.cc:47 : Going to execute Service: LANConfigSecurity with action: SetConfigPassword
[LOG:trace] Auth.cc:121 : Current state: IDLE
An error occured: Received response does not contain an envelope_node, unable to proceed, received: 
HTTP/1.1 401 Unauthorized
Connection: Keep-Alive
WWW-Authenticate: Digest realm="HuaweiHomeGateway",nonce="955cd72720e2bfcc406b1a842eb1ef06", qop="auth", algorithm="MD5"
Content-Length: 0

the app should now calculate the response and send a new request with the response on it  then it shall be auth and the action done 

can u please mail me on bossehab2010@gmail.com 
i need to give u some stuff that may help but i cannot post in public
thnxxxxxxxx

**Comment by awidegreen** [comment]
right .. I just changed it to use curl so far, gonna add a new parameter for the http digsest auth. Is the username and pw the same as for the SOAP authentication?

**Comment by awidegreen** [comment]
see manpage for contact info.

**Comment by ehabtanta** [comment]
"right .. I just changed it to use curl so far, gonna add a new parameter for the http digsest auth. Is the username and pw the same as for the SOAP authentication"

there are 2 username and pwd sets 
1st username is  :dslf-config  and its pwd is changeable the admin changed it in the current (new challenge) 
and it is responsible for all the actions and services of the tr064 but one service&one action  (the LANConfigSecurity:SetConfigPassword) that is only accessible using the 
2nd set of username :dslf-reset and its pwd in static cannot be changed most likely will be blank or admin 

so i need to use dslf-reset to change the dslf-config pwd and from the dslf-config i would setuserpassword and solve the challenge 

all i need is that the tool get the nonce from the 1st 401 reply and calculate a response that would be accepted by the tr064 server in the router 
will mail u some stuff that may help 
tnx alooooooooooooooooooot

**Comment by ehabtanta** [comment]
sent u a mail 
tnx

**Comment by ehabtanta** [comment]
will be w8ing the new branch 
thank you
