### ISSUE TITLE
Problem with Hosts:GetSpecificHostEntry

### ISSUE THREAD

**Issue by mbronni** [awidegreen/tr064#6]
Hello, I am running the tool on my raspberry pi. Very cool and useful thing. Unfortunately I can't query for a specific mac address on my network. 
I was trying: 
tr064tool -v --no-auth Hosts:GetSpecificHostEntry NewMACAddress:11:22:33:44:55:66
The following error comes back from my fritzbox: 
<errorCode>402</errorCode>
<errorDescription>Invalid Args</errorDescription>
I tried also uppercase/lowercase and "-" instead of ":"

The command:
tr064tool -v --no-auth Hosts:GetGenericHostEntry NewIndex:10
works perfectly. But I don't want to check devices on network. 

Then I have seen that the query command
<u:GetSpecificHostEntry xmlns:u="urn:dslforum-org:service:Hosts:1">
   <NewMACAddress>11:22:33:44:55:66       </NewMACAddress>
</u:GetSpecificHostEntry>
has some whitespace before the end tag of "NewMACAddress". 
Any idea what I am doing wrong?

**Comment by awidegreen** [comment]
Thanks for reporting, da738c3 fixes the issue.

**Comment by mbronni** [comment]
Thanks a lot !!! Works perfectly...
